const $=id=>document.getElementById(id),screens=[...document.querySelectorAll('.screen')],modal=$('modal');
const SETTINGS_KEY='quiet-creek-settings-v1',CYCLES=5;
const phases=[{id:'inhale',word:'BREATHE IN',title:'Breathe in gently',cue:'Pogo gets round and rosy.',ms:3500},{id:'exhale',word:'BUBBLES OUT',title:'Let the bubbles out',cue:'Easy and slow. Watch them float.',ms:5200},{id:'rest',word:'REST',title:'Rest',cue:'Take a normal breath.',ms:1400}];
let settings=loadSettings(),cycle=1,phaseIndex=0,elapsed=0,lastTime=0,frame=0,sessionActive=false,paused=false,audioContext=null,activeSound=null;
function loadSettings(){try{return{sound:false,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return{sound:false,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches}}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}catch{}}
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0)}
function phase(){return phases[phaseIndex]}
function stopSound(){if(activeSound){try{activeSound.stop()}catch{}activeSound=null}}
function updateControls(){document.body.classList.toggle('low-sensory',settings.reducedMotion);$('soundButton').setAttribute('aria-pressed',String(settings.sound));$('soundButton').setAttribute('aria-label',settings.sound?'Turn sound off':'Turn sound on');$('soundLabel').textContent=settings.sound?'Sound on':'Sound off';$('sensoryButton').setAttribute('aria-pressed',String(settings.reducedMotion));$('sensoryButton').setAttribute('aria-label',settings.reducedMotion?'Turn gentle motion on':'Reduce motion');$('sensoryLabel').textContent=settings.reducedMotion?'Motion reduced':'Gentle motion'}
function renderPhase(announce=false){const p=phase(),colors={inhale:'#68b96f',exhale:'#3d9f88',rest:'#27745b'};$('cycleText').textContent=p.id==='rest'?'Breath '+cycle+' of '+CYCLES+' · rest':'Breath '+cycle+' of '+CYCLES;$('phaseWordBase').textContent=p.word;$('phaseWordFill').textContent=p.word;$('phaseWordFill').style.setProperty('--phase-color',colors[p.id]);$('breath-title').textContent=p.title;$('phaseCue').textContent=p.cue;if(announce)$('phaseAnnouncer').textContent=p.title+'. '+p.cue}
function smooth(t){return t*t*(3-2*t)}
function renderProgress(){const p=phase(),progress=Math.min(1,elapsed/p.ms);$('phaseWordFill').style.setProperty('--progress',(progress*100).toFixed(2)+'%');const amount=p.id==='inhale'?smooth(progress):p.id==='exhale'?1-smooth(progress):0,body=document.querySelector('.pogo-body-wrap'),halo=document.querySelector('.breath-halo'),stage=document.querySelector('.pogo-stage'),red=[244,158,158],blue=[163,216,239],color=blue.map((v,i)=>Math.round(v+(red[i]-v)*amount));document.querySelector('.pogo-color').style.background='rgba('+color.join(',')+',.58)';stage.classList.toggle('is-exhaling',p.id==='exhale');document.querySelectorAll('.bubble').forEach((bubble,i)=>{const local=p.id==='exhale'?Math.max(0,Math.min(1,(progress-i*.11)/(1-i*.11))):0,fade=Math.sin(Math.PI*local);bubble.style.opacity=settings.reducedMotion?'0':String(Math.max(0,fade*.88));bubble.style.transform='translate('+Math.sin(local*8+i)*8+'px,'+(-local*(105+i*13))+'px) scale('+(0.72+local*.38)+')'});if(settings.reducedMotion){body.style.transform='none';halo.style.transform='none';halo.style.opacity='0'}else{body.style.transform='translateZ(0) scaleX('+(1+0.13*amount).toFixed(4)+') scaleY('+(1+0.15*amount).toFixed(4)+') rotate('+(Math.sin(progress*Math.PI)*.8)+'deg)';halo.style.transform='translateZ(0) scale('+(0.91+0.18*amount).toFixed(4)+')';halo.style.opacity=(0.38+0.34*amount).toFixed(3)}}
function makeCuteHiss(seconds){if(!settings.sound||phase().id!=='exhale')return;const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;try{audioContext||=new AudioCtor();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime,length=Math.ceil(audioContext.sampleRate*seconds),buffer=audioContext.createBuffer(1,length,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(.72+.28*Math.sin(i/175));const source=audioContext.createBufferSource(),high=audioContext.createBiquadFilter(),low=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;high.type='highpass';high.frequency.value=1250;low.type='lowpass';low.frequency.value=4300;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.014,now+.35);gain.gain.setValueAtTime(.014,now+Math.max(.4,seconds-.55));gain.gain.linearRampToValueAtTime(0,now+seconds);source.connect(high).connect(low).connect(gain).connect(audioContext.destination);source.start(now);source.stop(now+seconds);activeSound=source;source.onended=()=>{if(activeSound===source)activeSound=null}}catch{settings.sound=false;saveSettings();updateControls()}}
function beginPhase(announce=true){stopSound();renderPhase(announce);renderProgress();makeCuteHiss(phase().ms/1000)}
function advancePhase(){phaseIndex++;if(phaseIndex>=phases.length){if(cycle>=CYCLES){completeSession();return}cycle++;phaseIndex=0}beginPhase()}
function tick(now){if(!sessionActive||paused)return;elapsed+=Math.max(0,Math.min(100,now-lastTime));lastTime=now;while(sessionActive&&elapsed>=phase().ms){elapsed-=phase().ms;advancePhase()}if(sessionActive){renderProgress();frame=requestAnimationFrame(tick)}}
function startSession(){stopSession();cycle=1;phaseIndex=0;elapsed=0;paused=false;sessionActive=true;show('breathe');$('pauseButton').textContent='Ⅱ';$('pauseButton').setAttribute('aria-label','Pause');beginPhase();lastTime=performance.now();frame=requestAnimationFrame(tick)}
function stopSession(){cancelAnimationFrame(frame);stopSound();sessionActive=false;paused=false;elapsed=0}
function completeSession(){stopSession();show('complete');$('complete-title').focus()}
function openSettings(){$('modalContent').innerHTML='<h3>Grown-up settings</h3><p>Quiet Creek remembers these choices on this device.</p><button class="choice" id="modalSound"><span>♪</span><strong>'+(settings.sound?'Sound is on':'Sound is off')+'</strong></button><button class="choice" id="modalMotion"><span>◐</span><strong>'+(settings.reducedMotion?'Motion is reduced':'Gentle motion is on')+'</strong></button><p class="disclaimer">General wellness and educational use only—not medical advice or treatment. Stop if a child feels dizzy, short of breath, uncomfortable, or distressed.</p><button class="text-button" data-close>Done</button>';if(!modal.open)modal.showModal()}
$('meetPogoButton').onclick=()=>show('preview');$('startButton').onclick=startSession;$('replayButton').onclick=startSession;$('settingsButton').onclick=openSettings;
document.querySelectorAll('[data-back="home"]').forEach(b=>b.onclick=()=>{stopSession();show('home')});$('stopButton').onclick=()=>{stopSession();show('home')};
$('pauseButton').onclick=()=>{if(!sessionActive)return;paused=!paused;$('pauseButton').textContent=paused?'▶':'Ⅱ';$('pauseButton').setAttribute('aria-label',paused?'Resume':'Pause');if(paused){cancelAnimationFrame(frame);stopSound();$('phaseWordBase').textContent='PAUSED';$('phaseWordFill').textContent='PAUSED';$('phaseWordFill').style.setProperty('--progress','0%');$('phaseCue').textContent='Take a normal breath.';$('phaseAnnouncer').textContent='Paused. Take a normal breath.'}else{renderPhase(true);renderProgress();makeCuteHiss(Math.max(.1,(phase().ms-elapsed)/1000));lastTime=performance.now();frame=requestAnimationFrame(tick)}};
$('soundButton').onclick=()=>{settings.sound=!settings.sound;saveSettings();updateControls();if(settings.sound&&sessionActive&&!paused)makeCuteHiss(Math.max(.1,(phase().ms-elapsed)/1000));else stopSound()};
$('sensoryButton').onclick=()=>{settings.reducedMotion=!settings.reducedMotion;if(settings.reducedMotion)stopSound();saveSettings();updateControls();renderProgress()};
modal.addEventListener('click',e=>{if(e.target.closest('[data-close]'))modal.close();if(e.target.closest('#modalSound')){settings.sound=!settings.sound;saveSettings();updateControls();openSettings()}if(e.target.closest('#modalMotion')){settings.reducedMotion=!settings.reducedMotion;saveSettings();updateControls();openSettings()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&sessionActive&&!paused)$('pauseButton').click()});window.addEventListener('pagehide',stopSound);updateControls();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
